services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: equipe3-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: equipe3-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

