package com.equipe3.backend.web;

import com.equipe3.backend.service.AssetStorageService;
import com.equipe3.backend.service.IllustrationService;
import com.equipe3.backend.service.OneShotAssetsService;
import org.springframework.http.CacheControl;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.nio.file.Files;
import java.time.Duration;
import java.util.Map;

/** Serves the PNG assets generated by the OpenAI image pipeline. */
@RestController
@RequestMapping("/assets")
public class AssetController {

    private final AssetStorageService assets;
    private final OneShotAssetsService oneShot;
    private final IllustrationService illustrations;

    public AssetController(AssetStorageService assets, OneShotAssetsService oneShot,
                           IllustrationService illustrations) {
        this.assets = assets;
        this.oneShot = oneShot;
        this.illustrations = illustrations;
    }

    /**
     * The one-shot assets (avatars, UI icons) available right now, plus
     * whether image generation is enabled at all — the frontend keeps emoji
     * fallbacks for anything missing and skips polling when disabled.
     */
    @GetMapping("/manifest")
    public Map<String, Object> manifest() {
        return Map.of(
                "enabled", illustrations.isEnabled(),
                "assets", oneShot.manifest());
    }

    @GetMapping("/{file}")
    public ResponseEntity<byte[]> get(@PathVariable String file) throws IOException {
        var path = assets.resolve(file);
        if (path.isEmpty()) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok()
                .contentType(MediaType.IMAGE_PNG)
                .cacheControl(CacheControl.maxAge(Duration.ofHours(12)))
                .body(Files.readAllBytes(path.get()));
    }
}
